# Generated by Django 5.2.12 on 2026-03-21 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='music/')),
                ('genre', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('CLASSICAL', 'Classical'), ('METAL', 'Metal'), ('COUNTRY', 'Country')], max_length=20)),
                ('mood', models.CharField(choices=[('AMBITIOUS', 'Ambitious'), ('ANXIOUS', 'Anxious'), ('CALM', 'Calm'), ('CHEERFUL', 'Cheerful'), ('EXCITED', 'Excited'), ('HEARTBROKEN', 'Heartbroken')], max_length=20)),
                ('usage_occupation', models.CharField(max_length=100)),
                ('vocal_preference', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('generate_state', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='accounts.user')),
            ],
        ),
    ]
