# Generated by Django 5.2.12 on 2026-04-19 16:08

from django.db import migrations


def seed_genre_mood(apps, schema_editor):
    Genre = apps.get_model("musics", "Genre")
    Mood = apps.get_model("musics", "Mood")

    genres = ["Pop", "Rock", "Jazz", "Classical", "Metal", "Country"]
    moods = ["Ambitious", "Anxious", "Calm", "Cheerful", "Excited", "Heartbroken"]

    for g in genres:
        Genre.objects.get_or_create(name=g)

    for m in moods:
        Mood.objects.get_or_create(name=m)


def reverse_seed(apps, schema_editor):
    Genre = apps.get_model("musics", "Genre")
    Mood = apps.get_model("musics", "Mood")

    Genre.objects.all().delete()
    Mood.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("musics", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_genre_mood, reverse_seed),
    ]