# Generated by Django 5.2.12 on 2026-04-19 13:09

import musics.utilities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='music/', validators=[musics.utilities.validators.validate_audio_file, musics.utilities.validators.validate_file_size]),
        ),
    ]
