# Generated by Django 5.2.12 on 2026-04-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_seed_users_and_music'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='description',
            new_name='generate_description',
        ),
        migrations.AddField(
            model_name='music',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
