# Generated by Django 5.2.12 on 2026-04-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_rename_description_music_generate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='generator_strategy',
            field=models.CharField(choices=[('suno', 'Suno API'), ('mock', 'Mock Generator')], default='suno', max_length=20),
        ),
        migrations.AlterField(
            model_name='music',
            name='generate_state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
    ]
