# Generated by Django 5.2.12 on 2026-04-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0005_music_generator_strategy_alter_music_generate_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='generate_description',
            new_name='description',
        ),
    ]
