# Generated by Django 5.2.12 on 2026-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0006_rename_generate_description_music_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='music',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
