# Generated by Django 5.2.12 on 2026-04-24 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0007_remove_music_audio_file_music_audio_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musics.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
