# Generated by Django 5.2.12 on 2026-04-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0008_generationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='GenerationLog',
        ),
    ]
