# Generated by Django 5.2.12 on 2026-04-25 07:32

from django.db import migrations
from datetime import datetime, timezone

def seed_win_music(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Music = apps.get_model("musics", "Music")
    Genre = apps.get_model("musics", "Genre")
    Mood = apps.get_model("musics", "Mood")

    genre, _ = Genre.objects.get_or_create(name="Jazz")
    mood, _ = Mood.objects.get_or_create(name="Excited")
    
    # Ensure a Chithara dev user exists just in case
    dev_user, _ = User.objects.get_or_create(
        username="Chithara dev", 
        defaults={"email": "dev@chithara.com"}
    )

    users = User.objects.all()
    target_date = datetime(2026, 4, 20, 10, 6, tzinfo=timezone.utc)

    for user in users:
        music, m_created = Music.objects.get_or_create(
            owner=user,
            task_id="1032ba4f9b417a4bbba5cdddfdd534f1",
            defaults={
                "display_name": "WIN",
                "genre": genre,
                "mood": mood,
                "generate_state": "COMPLETED",
                "generator_strategy": "suno",
                "audio_url": "/media/WIN.mp3",
                "usage_occupation": "Theme Song",
                "vocal_preference": "Any",
                "description": "The official Chithara theme song.",
            }
        )
        if m_created:
            Music.objects.filter(id=music.id).update(created_at=target_date)

def reverse_seed(apps, schema_editor):
    Music = apps.get_model("musics", "Music")
    Music.objects.filter(task_id="1032ba4f9b417a4bbba5cdddfdd534f1").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0009_music_is_active_delete_generationlog'),
    ]

    operations = [
        migrations.RunPython(seed_win_music, reverse_seed),
    ]
